
name = "FefferyAntdComponents"
uuid = "1b08a953-4be3-4667-9a23-674b58f7de79"
authors = ["CNFeffery <fefferypzy@gmail.com>"]
version = "0.3.0-rc31"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
